collections:
  en-courses:
    sort_by: number
    output: true
    permalink: /:collection/:name

  en-handsons:
    sort_by: number
    output: true
    permalink: /:collection/:name

  en-results:
    sort_by: number
    output: true
    permalink: /:collection/:name

  fr-courses:
    sort_by: number
    output: true
    permalink: /:collection/:name

  fr-handsons:
    sort_by: number
    output: true
    permalink: /:collection/:name

  fr-results:
    sort_by: number
    output: true
    permalink: /:collection/:name
